version: '3'

volumes:
    db:

services:
    db:
        image: mysql:8
        container_name: leqg-db
        ports:
            - '3306:3306'
        environment:
            MYSQL_ROOT_PASSWORD: leqg
            MYSQL_DATABASE: leqg
        volumes:
            - db:/var/lib/mysql
